package co.feip.fefu2025.ui

object Constants {
    val programmingLanguages = listOf(
        "Kotlin",
        "Java",
        "Python",
        "C++",
        "C",
        "JavaScript",
        "Ruby",
        "Swift",
        "Objective-C",
        "PHP",
        "C#",
        "Go",
        "Rust",
        "Dart",
        "Scala",
        "Elixir",
        "Erlang",
        "Haskell",
        "Clojure",
        "F#",
        "TypeScript",
        "Perl",
        "R",
        "Lua",
        "MATLAB",
        "Groovy",
        "Visual Basic .NET",
        "Assembly",
        "Fortran",
        "COBOL",
        "Pascal",
        "Ada",
        "Prolog",
        "Lisp",
        "Julia",
        "Shell",
        "SQL",
        "PowerShell",
        "Objective-J",
        "CoffeeScript",
        "Crystal",
        "Nim",
        "D",
        "VHDL",
        "Verilog",
        "ABAP",
        "Delphi/Object Pascal",
        "LabVIEW",
        "Racket",
        "Forth"
    )
}